### ISSUE TITLE
关于运行pysot-toolkit  test.py

### ISSUE THREAD

**Issue by huade2022** [chenxin-dlut/TransT#145]
运行 python -u pysot_toolkit/test.py --dataset GOT-10k --name 'transt'出错
pysot_toolkit/..
Traceback (most recent call last):
File "pysot_toolkit/test.py", line 225, in <module>
main()
File "pysot_toolkit/test.py", line 52, in main
load_img=False)
File "/media/ygh/EXTERNAL_USB/huade/TransT-main/pysot_toolkit/toolkit/datasets/__init__.py", line 38, in create_dataset
dataset = GOT10kDataset(**kwargs)
File "/media/ygh/EXTERNAL_USB/huade/TransT-main/pysot_toolkit/toolkit/datasets/got10k.py", line 59, in __init__
meta_data = json.load(f)
File "/home/ygh/anaconda3/envs/transt/lib/python3.7/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/home/ygh/anaconda3/envs/transt/lib/python3.7/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 8: invalid continuation byte

**Comment by huade2022** [comment]
请问这个错误是什么原因？是因为json文件无法正常读取吗？
