### ISSUE TITLE
[Errno 13] Permission denied: '/tensorboard'

### ISSUE THREAD

**Issue by LeungWaiHo** [chenxin-dlut/TransT#47]
作者您好，我在运行python run_training.py transt transt时，出现了如标题所示的错误，请问该如何解决？
Traceback (most recent call last):
  File "run_training.py", line 55, in <module>
    main()
  File "run_training.py", line 50, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "run_training.py", line 39, in run_training
    expr_func(settings)
  File "../ltr/train_settings/transt/transt.py", line 98, in run
    trainer = LTRTrainer(actor, [loader_train], optimizer, settings, lr_scheduler)
  File "../ltr/trainers/ltr_trainer.py", line 30, in __init__
    self.tensorboard_writer = TensorboardWriter(tensorboard_writer_dir, [l.name for l in loaders])
  File "../ltr/admin/tensorboard.py", line 13, in __init__
    self.writer = OrderedDict({name: SummaryWriter(os.path.join(self.directory, name)) for name in loader_names})
  File "../ltr/admin/tensorboard.py", line 13, in <dictcomp>
    self.writer = OrderedDict({name: SummaryWriter(os.path.join(self.directory, name)) for name in loader_names})
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 225, in __init__
    self._get_file_writer()
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 256, in _get_file_writer
    self.flush_secs, self.filename_suffix)
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 66, in __init__
    log_dir, max_queue, flush_secs, filename_suffix)
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 653, in makedirs
    return get_filesystem(path).makedirs(path)
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 191, in makedirs
    os.makedirs(path, exist_ok=True)
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/lab318/anaconda3/envs/transt/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tensorboard'

**Comment by chenxin-dlut** [comment]
local.py里 tensorboard的路径设置的不对

**Comment by LeungWaiHo** [comment]
> local.py里 tensorboard的路径设置的不对

请问在哪里修改batchsize，因为我只有两张的2080ti

**Comment by chenxin-dlut** [comment]
train settings文件夹，transt.py

**Comment by LeungWaiHo** [comment]
> train settings文件夹，transt.py

如果工作站有4张卡，可以设置只用其中两张卡吗，例如gpu id这些

**Comment by chenxin-dlut** [comment]
可以，设置CUDA VISIBLE DEVICES即可

**Comment by LeungWaiHo** [comment]
已经可以跑起来了，谢谢
