### ISSUE TITLE
pysot_toolkit数据集测试

### ISSUE THREAD

**Issue by zcygzh** [chenxin-dlut/TransT#64]
您好，我用pysot测试GOT10k时可以，但是测试Lasot 和 Trackingnet 数据集时就会报错,请问您是如何配置的呢？

![image](https://user-images.githubusercontent.com/33140965/127514286-0520b24f-9ef2-4371-9c11-1ee48d7c7c55.png)
 robot@robot:~/project/TransT$ python -u pysot_toolkit/test.py --dataset TrackingNet --name 'transt'
pysot_toolkit/..
loading TrackingNet:   0%|                                   | 0/511 [00:00<?, ?it/s, 1s7hqoYecSo_0]
Traceback (most recent call last):
  File "pysot_toolkit/test.py", line 248, in <module>
    main()
  File "pysot_toolkit/test.py", line 58, in main
    load_img=False)
  File "pysot_toolkit/../pysot_toolkit/toolkit/datasets/__init__.py", line 36, in create_dataset
    dataset = TrackingNetDataset(**kwargs)
  File "pysot_toolkit/../pysot_toolkit/toolkit/datasets/trackingnet.py", line 73, in __init__
    None)
  File "pysot_toolkit/../pysot_toolkit/toolkit/datasets/trackingnet.py", line 25, in __init__
    init_rect, img_names, gt_rect, attr, load_img)
  File "pysot_toolkit/../pysot_toolkit/toolkit/datasets/video.py", line 27, in __init__
    assert img is not None, self.img_names[0]
AssertionError: /media/robot/T2/trackingNet/TEXT/1s7hqoYecSo_0/0.jpg

**Comment by chenxin-dlut** [comment]
这个是说这张图片是none，检察一下数据集里这张图片有没有问题，或者数据集路径是否正确

**Comment by zcygzh** [comment]
> 这个是说这张图片是none，检察一下数据集里这张图片有没有问题，或者数据集路径是否正确

谢谢提醒~
