### ISSUE TITLE
when running " python run_training.py transt transt" An execution problem occurred

### ISSUE THREAD

**Issue by qiqichen77** [chenxin-dlut/TransT#99]
Traceback (most recent call last):
  File "D:\ADeepLearning\TransT-main\ltr\trainers\base_trainer.py", line 70, in train
    self.train_epoch()
  File "D:\ADeepLearning\TransT-main\ltr\trainers\ltr_trainer.py", line 79, in train_epoch
    self.cycle_dataset(loader)
  File "D:\ADeepLearning\TransT-main\ltr\trainers\ltr_trainer.py", line 60, in cycle_dataset
    loss, stats = self.actor(data)
  File "D:\ADeepLearning\TransT-main\ltr\actors\tracking.py", line 41, in __call__
    loss_dict = self.objective(outputs, targets)
  File "C:\Users\ASUS2\anaconda3\envs\transt\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ADeepLearning\TransT-main\ltr\models\tracking\transt.py", line 204, in forward
    losses.update(self.get_loss(loss, outputs, targets, indices, num_boxes_pos))
  File "D:\ADeepLearning\TransT-main\ltr\models\tracking\transt.py", line 180, in get_loss
    return loss_map[loss](outputs, targets, indices, num_boxes)
  File "D:\ADeepLearning\TransT-main\ltr\models\tracking\transt.py", line 127, in loss_labels
    target_classes[idx] = target_classes_o
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.

**Comment by LinYang-mak** [comment]
Traceback for the error!
Traceback (most recent call last):
  File "E:\YL\Algorithm_Code\TransT\TransT-main\ltr\trainers\base_trainer.py", line 70, in train
    self.train_epoch()
  File "E:\YL\Algorithm_Code\TransT\TransT-main\ltr\trainers\ltr_trainer.py", line 79, in train_epoch
    self.cycle_dataset(loader)
  File "E:\YL\Algorithm_Code\TransT\TransT-main\ltr\trainers\ltr_trainer.py", line 52, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "D:\SoftInstall\Anaconda\install\envs\transt\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\SoftInstall\Anaconda\install\envs\transt\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\SoftInstall\Anaconda\install\envs\transt\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\SoftInstall\Anaconda\install\envs\transt\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\YL\Algorithm_Code\TransT\TransT-main\ltr\data\sampler.py", line 93, in __getitem__
    dataset = random.choices(self.datasets, self.p_datasets)[0]
  File "D:\SoftInstall\Anaconda\install\envs\transt\lib\random.py", line 361, in choices
    raise ValueError('The number of weights does not match the population')
ValueError: The number of weights does not match the population

**Comment by MENGM0** [comment]
> does

我修改成自己的数据集，也遇到相同的情况.

**Comment by JYing7** [comment]
> Traceback (most recent call last): File "D:\ADeepLearning\TransT-main\ltr\trainers\base_trainer.py", line 70, in train self.train_epoch() File "D:\ADeepLearning\TransT-main\ltr\trainers\ltr_trainer.py", line 79, in train_epoch self.cycle_dataset(loader) File "D:\ADeepLearning\TransT-main\ltr\trainers\ltr_trainer.py", line 60, in cycle_dataset loss, stats = self.actor(data) File "D:\ADeepLearning\TransT-main\ltr\actors\tracking.py", line 41, in **call** loss_dict = self.objective(outputs, targets) File "C:\Users\ASUS2\anaconda3\envs\transt\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "D:\ADeepLearning\TransT-main\ltr\models\tracking\transt.py", line 204, in forward losses.update(self.get_loss(loss, outputs, targets, indices, num_boxes_pos)) File "D:\ADeepLearning\TransT-main\ltr\models\tracking\transt.py", line 180, in get_loss return loss_map[loss](outputs, targets, indices, num_boxes) File "D:\ADeepLearning\TransT-main\ltr\models\tracking\transt.py", line 127, in loss_labels target_classes[idx] = target_classes_o RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.

我也遇到了同意的问题，想问你解决了吗？
